"""
Game Reviews Database Schema

This module defines the schema for storing post-game reviews generated by OpenAI Vision.
Reviews include actual scores extracted from screenshots and AI-generated analysis.

Tables:
- game_reviews: Post-game review data with AI analysis

Usage:
    from api.utils.db_schema_game_reviews import init_game_reviews_db
    init_game_reviews_db()
"""

import sqlite3
from datetime import datetime
from contextlib import contextmanager

# Import centralized database configuration
try:
    from api.utils.db_config import get_db_path
except ImportError:
    from db_config import get_db_path

# Database file location
GAME_REVIEWS_DB_PATH = get_db_path('game_reviews.db')


@contextmanager
def get_connection():
    """Get a connection to the game reviews database"""
    conn = sqlite3.connect(GAME_REVIEWS_DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()


def init_game_reviews_db():
    """
    Initialize the game reviews database schema.
    Creates all tables and indexes if they don't exist.
    """
    with get_connection() as conn:
        cursor = conn.cursor()

        # ====================================================================
        # GAME REVIEWS TABLE (Post-game analysis with OpenAI Vision)
        # ====================================================================
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS game_reviews (
                game_id TEXT PRIMARY KEY,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                game_date TEXT NOT NULL,

                -- Actual scores (extracted from screenshot via OpenAI Vision)
                actual_home_score INTEGER,
                actual_away_score INTEGER,
                actual_total INTEGER,

                -- Predicted values (from our model before the game)
                predicted_home_score REAL,
                predicted_away_score REAL,
                predicted_total REAL,
                sportsbook_line REAL,  -- Betting line used for WIN/LOSS determination

                -- Vision extraction metadata
                vision_confidence TEXT,  -- "high", "medium", "low"
                vision_model TEXT,  -- e.g., "gpt-4.1"
                vision_raw_response TEXT,  -- Full JSON response from Vision API

                -- Error analysis
                error_home REAL,  -- actual_home - predicted_home
                error_away REAL,  -- actual_away - predicted_away
                error_total REAL,  -- actual_total - predicted_total
                abs_error_total REAL,  -- abs(error_total)

                -- AI-generated review (from text model)
                ai_review_json TEXT,  -- JSON with what_happened, why_we_missed, key_factors
                ai_review_model TEXT,  -- e.g., "gpt-4.1-mini"

                -- Style stats comparison (per-team detailed stats)
                expected_style_stats_json TEXT,  -- JSON with expected stats for both teams
                actual_style_stats_json TEXT,  -- JSON with actual stats for both teams

                -- Metadata
                screenshot_filename TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
        ''')

        # Index for querying by date
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_game_reviews_date
            ON game_reviews(game_date)
        ''')

        # Index for querying by error magnitude (for finding biggest misses)
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_game_reviews_abs_error
            ON game_reviews(abs_error_total)
        ''')

        conn.commit()
        print(f"[DB] Game reviews database initialized at: {GAME_REVIEWS_DB_PATH}")


if __name__ == '__main__':
    # Initialize database when run directly
    init_game_reviews_db()
